Added output of temperature information using "RecyclerView"
tomasz-ludek/pool-office-client pull request #10
Opened 2022-07-29 22:00 UTC by Sergey90K

2022-08-02 12:01 UTC, tomasz-ludek requested changes
Looks good!
Few minor things to fix, though.

2022-08-02 12:01 UTC, tomasz-ludek commented on app/src/main/java/pl/ludek/smat/home/pool_office_client/presentation/MainActivity.kt
> +                val recyclerView: RecyclerView = findViewById(R.id.recyclerViewPoolInfo)
PLease use `binding.recyclerViewPoolInfo` instead of `findViewById(R.id.recyclerViewPoolInfo)`

2022-08-02 12:01 UTC, tomasz-ludek commented on app/src/main/java/pl/ludek/smat/home/pool_office_client/presentation/CustomAdapter.kt
> +            textView = view.findViewById(R.id.textView)
You can use View Binding instead of `findViewById` inside the `RecyclerView.ViewHolder` please do it.

2022-08-02 19:50 UTC, Sergey90K commented
Found bugs fixed

2022-08-03 10:44 UTC, tomasz-ludek approved these changes
Well done!

2022-08-03 10:44 UTC, merged